openapi: "3.0.2"
info:
  title: Описание API для бюджета
  version: "1.0"
servers:
  - url: https://api.server.test/v1
tags:
  - name: "API бюджета"
    description: "API бюджета пользователя"
components:
  parameters:
    budget_id:
      name: 'id'
      in: 'path'
      description: 'Уникальный ключ бюджета'
      required: true
      schema:
        type: integer
    user_id:
      name: 'user_id'
      in: 'query'
      description: 'Уникальный ключ Пользователя'
      required: false
      schema:
        type: integer
    category_id:
      name: 'category_id'
      in: 'query'
      description: 'Уникальный ключ Категории'
      required: false
      schema:
        type: integer
    budget_date_start:
      name: 'budget_date_start'
      in: 'query'
      description: 'Начальная дата бюджета'
      required: false
      schema:
        type: string
        format: date
    budget_date_finish:
      name: 'budget_date_finish'
      in: 'query'
      description: 'Конечная дата бюджета'
      required: false
      schema:
        type: string
        format: date
  schemas:
    User:
      type: object
      description: "Пользователь"
      properties:
        id:
          type: integer
          description: "Уникальный ключ"
        name:
          type: string
          description: "Имя пользователя"
    Category:
      type: object
      description: 'Категория'
      required:
        - id
        - name
      properties:
        id:
          type: integer
          description: "Уникальный ключ"
        name:
          type: string
          description: "Название операции"
    Budget:
      type: object
      description: "Бюджет пользователя"
      required:
        - id
        - sum
        - category
        - start_date
        - user
      properties:
        id:
          type: integer
          description: "Уникальный ключ"
        category:
          $ref: "#/components/schemas/Category"
        sum:
          type: number
          format: float
          description: "Сумма"
        start_date:
          type: string
          format: date
          description: "Дата начала актуальности бюджета"
        finish_date:
          type: string
          format: date
          description: "Дата окончания актуальности бюджета"
        user:
          $ref: "#/components/schemas/User"
    BudgetUpdate:
      type: object
      description: "Обновление бюджета пользователя"
      properties:
        category:
          type: integer
          description: "Категория бюджета"
        sum:
          type: integer
          description: "Сумма бюджета"
        start_date:
          type: string
          format: date
          description: "Дата начала актуальности бюджета"
        finish_date:
          type: string
          format: date
          description: "Дата окончания актуальности бюджета"
    BudgetCreate:
      type: object
      description: "Создание бюджета пользователя"
      required:
        - category
        - sum
        - start_date
      properties:
        category:
          type: integer
          description: "Категория бюджета"
        sum:
          type: integer
          description: "Сумма бюджета"
        start_date:
          type: string
          format: date
          description: "Дата начала актуальности бюджета"
        finish_date:
          type: string
          format: date
          description: "Дата окончания актуальности бюджета"
  responses:
    success:
      description: 'Успешная операция'
      content:
        application/json:
          schema:
            type: string
paths:
  /budget:
    get:
      description: "Получение списка бюджета операций пользователя"
      tags:
        - API бюджета
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/category_id'
        - $ref: '#/components/parameters/budget_date_start'
        - $ref: '#/components/parameters/budget_date_finish'
      responses:
        '200':
          description: 'Успешная операция'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Budget'
    post:
      description: 'Создание бюджета пользователя'
      tags:
        - API бюджета
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BudgetCreate'
      responses:
        '200':
          $ref: '#/components/responses/success'
  /budget/{id}:
    parameters:
      - $ref: '#/components/parameters/budget_id'
    get:
      tags:
        - API бюджета
      description: "Получение бюджета"
      responses:
        '200':
          description: 'Успешная операция'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Budget'
    put:
      tags:
        - API бюджета
      description: 'Обновление бюджета'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BudgetCreate'
      responses:
        '200':
          $ref: '#/components/responses/success'
    delete:
      description: 'Удаление бюджета'
      tags:
        - API бюджета
      responses:
        '200':
          $ref: '#/components/responses/success'
