openapi: "3.0.2"
info:
  title: Описание API для операций
  version: "1.0"
servers:
  - url: https://api.server.test/v1
tags:
  - name: "API операций"
    description: "API операций пользователя"
components:
  schemas:
    Balance:
      type: integer
      description: 'Баланс пользователя'
    BalanceDetailed:
      type: object
      description: 'Детальный баланс пользователя'
      properties:
        spending:
          type: array
          description: 'Траты пользователя'
          items:
            $ref: "#/components/schemas/CategoryDetailed"
        refill:
          type: array
          description: 'Поступления пользователя'
          items:
            $ref: "#/components/schemas/CategoryDetailed"
        balance:
          type: integer
          description: 'Баланс'
    Category:
      type: object
      description: "Категория операции"
      properties:
        id:
          type: integer
          description: "Уникальный ключ"
        name:
          type: string
          description: "Название категории"
    CategoryCreate:
      type: object
      description: "Создание категории операции"
      required:
        - name
      properties:
        name:
          type: string
          description: "Название категории"
    CategoryDetailed:
      type: object
      description: "Детальная информация о сумме операций в разрезе категории"
      properties:
        name:
          type: string
          description: "Название категории"
        sum:
          type: number
          format: float
          description: "Сумма операций"
    CategoryUpdate:
      type: object
      description: "Обновление категория операции"
      properties:
        name:
          type: string
          description: "Название категории"
    Operation:
      type: object
      description: 'Операция пользователя'
      required:
        - id
        - name
        - operation_type
        - date
      properties:
        id:
          type: integer
          description: "Уникальный ключ"
        name:
          type: string
          description: "Название операции"
        operation_type:
          type: string
          description: "Тип операции"
        description:
          type: string
          description: "Описание операции"
        cost:
          type: number
          format: float
          description: "Стоимость операции"
        date:
          type: string
          format: date-time
          description: "Дата и время операции"
        category:
          type: array
          description: "Список категорий операций"
          items:
            $ref: "#/components/schemas/OperationCategory"
    OperationCategory:
      type: object
      description: 'Категория операции'
      required:
        - id
        - name
      properties:
        id:
          type: integer
          description: "Уникальный ключ"
        name:
          type: string
          description: "Название операции"
    OperationCreate:
      type: object
      description: 'Создание операции пользователя'
      required:
        - name
        - operation_type
        - date
        - cost
      properties:
        name:
          type: string
          description: "Название операции"
        operation_type:
          type: string
          description: "Тип операции"
        description:
          type: string
          description: "Описание операции"
        cost:
          type: number
          format: float
          description: "Стоимость операции"
        date:
          type: string
          format: date-time
          description: "Дата и время операции"
        category:
          type: array
          description: "Список категорий операции"
          items:
            type: integer
        user:
          type: integer
          description: "Уникальный ключ пользователя"
    OperationUpdate:
      type: object
      description: 'Обновление операции пользователя'
      properties:
        name:
          type: string
          description: "Название операции"
        description:
          type: string
          description: "Описание операции"
        cost:
          type: number
          format: float
          description: "Стоимость операции"
        date:
          type: string
          format: date-time
          description: "Дата и время операции"
        category:
          type: array
          description: "Список категорий операции"
          items:
            type: integer
        user:
          type: integer
          description: "Уникальный ключ пользователя"
    User:
      type: object
      description: "Пользователь"
      properties:
        id:
          type: integer
          description: "Уникальный ключ"
        name:
          type: string
          description: "Имя пользователя"
  parameters:
    operation_id:
      name: 'id'
      in: 'path'
      description: 'Уникальный ключ операций'
      required: true
      schema:
        type: integer
    user_id:
      name: 'user_id'
      in: 'query'
      description: 'Уникальный ключ Пользователя'
      required: false
      schema:
        type: integer
    category_id:
      name: 'category_id'
      in: 'query'
      description: 'Уникальный ключ Категории'
      required: false
      schema:
        type: integer
    operation_date_start:
      name: 'operation_date_start'
      in: 'query'
      description: 'Начальная дата и время операции'
      required: false
      schema:
        type: string
        format: date-time
    operation_date_finish:
      name: 'operation_date_finish'
      in: 'query'
      description: 'Конечная дата и время операции'
      required: false
      schema:
        type: string
        format: date-time
    operation_type:
      name: 'operation_type'
      in: 'query'
      description: 'Тип операции'
      schema:
        type: string
        enum:
          - "Трата"
          - "Пополнение"
  responses:
    success:
      description: 'Успешная операция'
      content:
        application/json:
          schema:
            type: string
paths:
  /operations:
    get:
      description: 'Получение списка операций пользователя'
      tags:
        - API операций
      parameters:
        - $ref: '#/components/parameters/user_id'
        - $ref: '#/components/parameters/operation_type'
        - $ref: '#/components/parameters/category_id'
        - $ref: '#/components/parameters/operation_date_start'
        - $ref: '#/components/parameters/operation_date_finish'
      responses:
        '200':
          description: 'Успешная операция'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Operation'
    post:
      description: 'Создание операции пользователя'
      tags:
        - API операций
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OperationCreate'
      responses:
        '200':
          $ref: '#/components/responses/success'
  /operations/{id}:
    parameters:
      - $ref: '#/components/parameters/operation_id'
    get:
      tags:
        - API операций
      description: 'Получение операции'
      responses:
        '200':
          $ref: '#/components/schemas/Operation'
    put:
      tags:
        - API операций
      description: 'Обновление операции'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OperationUpdate'
      responses:
        '200':
          $ref: '#/components/responses/success'
    delete:
      description: 'Удаление операции'
      tags:
        - API операций
      responses:
        '200':
          $ref: '#/components/responses/success'
  /balance:
    get:
      description: 'Получение информации о балансе'
      tags:
        - API операций
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        '200':
          description: 'Успешная операция'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
  /balance-detailed:
    get:
      description: 'Детальная информация о балансе'
      tags:
        - API операций
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        '200':
          description: 'Успешная операция'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceDetailed'
  /category:
    get:
      description: 'Получение списка категорий'
      tags:
        - API операций
      responses:
        '200':
          description: 'Успешная операция'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      description: 'Создание категории'
      tags:
        - API операций
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryCreate'
      responses:
        '200':
          $ref: '#/components/responses/success'
  /category/{categoy_id}:
    parameters:
      - $ref: '#/components/parameters/category_id'
    get:
      tags:
        - API операций
      description: 'Получение категории'
      responses:
        '200':
          description: 'Успешная операция'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
    put:
      tags:
        - API операций
      description: 'Обновление категории'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryUpdate'
      responses:
        '200':
          $ref: '#/components/responses/success'
    delete:
      description: 'Удаление категории'
      tags:
        - API операций
      responses:
        '200':
          $ref: '#/components/responses/success'
