# Generated by Django 4.1.4 on 2022-12-28 16:26

from django.db import migrations, models
import server.app.operations.validation


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_operation_category_alter_operation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='cost',
            field=models.FloatField(validators=[server.app.operations.validation.validate_operation_cost], verbose_name='Стоимость'),
        ),
    ]
