# Generated by Django 4.1.4 on 2022-12-29 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_alter_operation_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="operations.category",
                verbose_name="Категория операции",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание операции"
            ),
        ),
    ]
