# Generated by Django 4.1.4 on 2022-12-22 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goals", "0003_alter_goal_goal_type_alter_goal_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="rule",
            field=models.CharField(
                choices=[
                    ("Меньше", "Lt"),
                    ("Меньше или равно", "Lte"),
                    ("Равно", "Eq"),
                    ("Больше", "Gt"),
                    ("Больше или равно", "Gte"),
                ],
                default="Равно",
                max_length=16,
                verbose_name="Правило достижения цели",
            ),
        ),
        migrations.RemoveField(
            model_name="goal",
            name="user",
        ),
        migrations.AddField(
            model_name="goal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелей цели",
            ),
            preserve_default=False,
        ),
    ]
