name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
      - uses: akaihola/darker@1.6.1
        with:
          options: "--check --diff --isort --color"
          version: "~=1.6.1"
          lint: "flake8,pylint==2.13.1,mypy==0.991"